Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,7 +2,7 @@ name: CI/CD Pipeline
 
 on:
   push:
-    branches: [ main ]
+    branches: [ aws-deploy ]
 
 env:
   AWS_REGION: ${{ secrets.AWS_REGION }}
@@ -85,8 +85,9 @@ jobs:
 
     - name: Load and push Docker image
       run: |
+        ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
         IMAGE_NAME=${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
-        IMAGE_URI=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME
+        IMAGE_URI=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME
 
         docker load -i image.tar
         docker tag $IMAGE_NAME $IMAGE_URI
@@ -133,5 +134,5 @@ jobs:
 
     - name: Deploy to EKS
       run: |
-        kubectl set image deployment/login-app login-app=$IMAGE_URI --record || echo "Deployment not found."
-
+        kubectl set image deployment/login-app-backend backend=$IMAGE_URI --record || echo "⚠️ Backend deployment not found."
+        kubectl set image deployment/login-app-frontend frontend=$IMAGE_URI --record || echo "⚠️ Frontend deployment not found."
